### PR TITLE
Use CSS variables, too

### PR DESCRIPTION
**Pull request by abejfehr**
This will allow people to use the variables without needing to build the SCSS first. Unfortunately this doesn't do anything for the mixins.

I also committed the updated `fabric-stats.md` and `package-lock.json` since those were out of date.

### CODE REVIEW

**Comment by benjyblack** [comment]
I have an admittedly limited knowledge of this stuff, but how does this allow us to use the variables without needing to build the SCSS? The CSS Variables still reference SCSS variables, which I assume will need to be built 🤔 .

**Comment by cchawn** [comment]
@benjyblack in the Fabric build we compile the SCSS down to [CSS](https://github.com/wealthsimple/fabric/blob/a697db8ece271f3ea2ab0605cd8d0e4fd9f7cc82/css/fabric.css) - so that means that the plain CSS variables would be available in that file. So someone including this in their project would be able to reference `fabric.css` and use those CSS variables in their own code without having to write their own stuff in SCSS and building it. (If that makes sense).

Take a look at [`fabric.css`](https://github.com/wealthsimple/fabric/blob/a697db8ece271f3ea2ab0605cd8d0e4fd9f7cc82/css/fabric.css) and you can see the new variables that Abe defined right at the beginning of the file

**Comment by benjyblack** [comment]
Ohh I see. So this allows consumers of fabric to use our variables without having to use SCSS. 👍 

It would be great if we could have a build step that does this for us instead of trying to remember to create a CSS variable every time we add a new SCSS variable.

Miiight be worth considering something like [this](https://www.npmjs.com/package/sass-to-css-variables)? But I guess we don't add variables very often so it's not a big deal.

**Comment by abejfehr** [comment]
@benjyblack I agree that it would be cool to do this in an automated way! Before doing this I Googled to see if the SCSS transpiler automatically turned SCSS variables into CSS ones, but that's not the case (currently).

If we find ourselves adding a ton of variables we might need to use the package you posted.

**Pull request merged**
